python3 lxml requires utf8 handling before writing.
Otherwise, it fails with:
xmlFile.write(etree.tostring(root, pretty_print=True, xml_declaration=True, doctype="<!DOCTYPE FixturesMap>"))
TypeError: write() argument must be str, not bytes